image: "python:latest"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Linting
  - Test

pylint:
  stage: Linting
  allow_failure: true
  tags:
    - gagas
  script:
    - pylint -d C0301 C0114 C0200 src/*.py

pytest:
  stage: Test
  tags:
    - gagas
  script:
  - cd test/;pytest -v