# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addTanaman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class UI_addTanaman(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMouseTracking(False)
        self.bgwidget.setAutoFillBackground(False)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: white;}")
        self.bgwidget.setObjectName("bgwidget")

        # BAGIAN NAVBAR
        # TODO : Ganti sama navbar yang bener
        self.navbar = QtWidgets.QFrame(self.bgwidget)
        self.navbar.setGeometry(QtCore.QRect(-1, 0, 1211, 91))
        self.navbar.setStyleSheet("QFrame#navbar{\n"
"    background-color: rgb(234, 216, 202);\n"
"   \n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")

        # NAVIGATION BAR
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.frame_2 = QtWidgets.QFrame(self.navbar)
        self.frame_2.setGeometry(QtCore.QRect(-10, -30, 1211, 51))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: rgb(136, 179, 160);\n"
"   \n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Logo = QtWidgets.QLabel(self.navbar)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 281, 121))
        self.Logo.setStyleSheet("font: 87 26pt \"Sansita\";\n"
"color : rgb(0, 0, 0) ")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("././img/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.berandaButton = QtWidgets.QPushButton(self.navbar)
        self.berandaButton.setGeometry(QtCore.QRect(350, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.berandaButton.setFont(font)
        self.berandaButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.berandaButton.setCheckable(False)
        self.berandaButton.setObjectName("berandaButton")
        self.tanamanButton = QtWidgets.QPushButton(self.navbar)
        self.tanamanButton.setGeometry(QtCore.QRect(520, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.tanamanButton.setFont(font)
        self.tanamanButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color :  rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.tanamanButton.setCheckable(False)
        self.tanamanButton.setObjectName("tanamanButton")
        self.aboutButton = QtWidgets.QPushButton(self.navbar)
        self.aboutButton.setGeometry(QtCore.QRect(670, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.aboutButton.setCheckable(False)
        self.aboutButton.setObjectName("aboutButton")
        self.search = QtWidgets.QLabel(self.navbar)
        self.search.setGeometry(QtCore.QRect(930, 40, 31, 31))
        self.search.setText("")
        self.search.setPixmap(QtGui.QPixmap("././img/Search.png"))
        self.search.setScaledContents(True)
        self.search.setObjectName("search")
        self.account = QtWidgets.QLabel(self.navbar)
        self.account.setGeometry(QtCore.QRect(980, 35, 31, 41))
        self.account.setText("")
        self.account.setPixmap(QtGui.QPixmap("././img/User.png"))
        self.account.setScaledContents(True)
        self.account.setObjectName("account")
        self.notification = QtWidgets.QLabel(self.navbar)
        self.notification.setGeometry(QtCore.QRect(1030, 40, 31, 31))
        self.notification.setText("")
        self.notification.setPixmap(QtGui.QPixmap("././img/Doorbell.png"))
        self.notification.setScaledContents(True)
        self.notification.setObjectName("notification")
        self.keranjang = QtWidgets.QLabel(self.navbar)
        self.keranjang.setGeometry(QtCore.QRect(1080, 30, 31, 51))
        self.keranjang.setText("")
        self.keranjang.setPixmap(QtGui.QPixmap("././img/Shopping Cart.png"))
        self.keranjang.setScaledContents(True)
        self.keranjang.setObjectName("keranjang")

        # Label Nama Tanaman
        self.namaTanamanLabel = QtWidgets.QLabel(self.bgwidget)
        self.namaTanamanLabel.setGeometry(QtCore.QRect(40, 120, 188, 33))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.namaTanamanLabel.setFont(font)
        self.namaTanamanLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.namaTanamanLabel.setObjectName("namaTanamanLabel")
        
        # Label Upload Foto
        self.uploadFotoLabel = QtWidgets.QLabel(self.bgwidget)
        self.uploadFotoLabel.setGeometry(QtCore.QRect(40, 190, 161, 31))
        self.uploadFotoLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.uploadFotoLabel.setObjectName("uploadFotoLabel")
        
        # Label Stok
        self.stokLabel = QtWidgets.QLabel(self.bgwidget)
        self.stokLabel.setGeometry(QtCore.QRect(40, 450, 171, 33))
        self.stokLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.stokLabel.setObjectName("stokLabel")

        # Label Domisili
        self.domisiliLabel = QtWidgets.QLabel(self.bgwidget)
        self.domisiliLabel.setGeometry(QtCore.QRect(310, 260, 751, 151))
        self.domisiliLabel.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;")
        self.domisiliLabel.setText("")
        self.domisiliLabel.setObjectName("domisiliLabel")
        
        # Button Tambahkan Tanaman
        self.tambahkanTanamanButton = QtWidgets.QPushButton(self.bgwidget)
        self.tambahkanTanamanButton.setGeometry(QtCore.QRect(500, 700, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        self.tambahkanTanamanButton.setFont(font)
        self.tambahkanTanamanButton.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"     background-color : rgb(85, 170, 127);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.tambahkanTanamanButton.setCheckable(False)
        self.tambahkanTanamanButton.setObjectName("tambahkanTanamanButton")

        # Label Deskripsi
        self.deskripsiLabel = QtWidgets.QLabel(self.bgwidget)
        self.deskripsiLabel.setGeometry(QtCore.QRect(40, 260, 161, 31))
        self.deskripsiLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.deskripsiLabel.setObjectName("deskripsiLabel")

        # Label Harga
        self.hargaLabel = QtWidgets.QLabel(self.bgwidget)
        self.hargaLabel.setGeometry(QtCore.QRect(40, 520, 190, 33))
        self.hargaLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.hargaLabel.setObjectName("hargaLabel")

        # Label domisili
        self.domisiliLabel = QtWidgets.QLabel(self.bgwidget)
        self.domisiliLabel.setGeometry(QtCore.QRect(40, 590, 211, 33))
        self.domisiliLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.domisiliLabel.setObjectName("domisiliLabel")

        # Button Upload Foto
        self.uploadFotoButton = QtWidgets.QPushButton(self.bgwidget)
        self.uploadFotoButton.setGeometry(QtCore.QRect(610, 190, 51, 41))
        self.uploadFotoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("././img/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadFotoButton.setIcon(icon)
        self.uploadFotoButton.setIconSize(QtCore.QSize(40, 40))
        self.uploadFotoButton.setFlat(True)
        self.uploadFotoButton.setObjectName("uploadFotoButton")

        # Line Edit Upload Foto
        # TODO : Ambil path file dari uploadFotoButton
        self.uploadFotoEdit = QtWidgets.QLabel(self.bgwidget)
        self.uploadFotoEdit.setGeometry(QtCore.QRect(310, 190, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.uploadFotoEdit.setFont(font)
        self.uploadFotoEdit.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : #769D8A;\n"
"    padding: 5px;")
        self.uploadFotoEdit.setText("path file")
        self.uploadFotoEdit.setObjectName("uploadFotoEdit")
        
        # Text Edit Deskripsi
        # TODO : sesuain textedit kayak lineedit
        self.textEdit = QtWidgets.QTextEdit(self.bgwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 260, 751, 151))
        self.textEdit.setObjectName("textEdit")
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color : #769D8A;")

        # Line Edit Nama
        self.namaTanamanEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.namaTanamanEdit.setGeometry(QtCore.QRect(310, 120, 301, 41))
        self.namaTanamanEdit.setStyleSheet("QLineEdit#namaTanamanEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.namaTanamanEdit.setText("")
        self.namaTanamanEdit.setObjectName("namaTanamanEdit")
        
        # Line Edit Stok
        self.stokEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.stokEdit.setGeometry(QtCore.QRect(310, 450, 211, 41))
        self.stokEdit.setStyleSheet("QLineEdit#stokEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.stokEdit.setText("")
        self.stokEdit.setObjectName("stokEdit")

        # Line Edit Harga
        self.hargaEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.hargaEdit.setGeometry(QtCore.QRect(310, 520, 211, 41))
        self.hargaEdit.setStyleSheet("QLineEdit#hargaEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.hargaEdit.setText("")
        self.hargaEdit.setObjectName("hargaEdit")

        # Line Edit Domisili
        self.domisiliEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.domisiliEdit.setGeometry(QtCore.QRect(310, 590, 211, 41))
        self.domisiliEdit.setStyleSheet("QLineEdit#domisiliEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.domisiliEdit.setText("")
        self.domisiliEdit.setObjectName("domisiliEdit")

        self.domisiliEdit.raise_()
        self.hargaEdit.raise_()
        self.stokEdit.raise_()
        self.namaTanamanEdit.raise_()
        self.navbar.raise_()
        self.namaTanamanLabel.raise_()
        self.uploadFotoLabel.raise_()
        self.stokLabel.raise_()
        self.domisiliLabel.raise_()
        self.tambahkanTanamanButton.raise_()
        self.deskripsiLabel.raise_()
        self.hargaLabel.raise_()
        self.domisiliLabel.raise_()
        self.uploadFotoButton.raise_()
        self.textEdit.raise_()
        self.uploadFotoEdit.raise_()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def pushButton_handler(self):
        print("Button pressed")
        self.open_dialog_box()

    # TODO : save pathnya lempar ke label
    def open_dialog_box(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        path = filename[0]
        print(path)

        with open(path, "r") as f:
            print(f.readline())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.berandaButton.setText(_translate("Dialog", "Beranda"))
        self.tanamanButton.setText(_translate("Dialog", "Tanaman"))
        self.aboutButton.setText(_translate("Dialog", "Tentang Kami"))
        self.namaTanamanLabel.setText(_translate("Dialog", "Nama Tanaman"))
        self.uploadFotoLabel.setText(_translate("Dialog", "Upload Foto"))
        self.uploadFotoButton.clicked.connect(self.pushButton_handler)
        self.stokLabel.setText(_translate("Dialog", "Stok Tanaman"))
        self.tambahkanTanamanButton.setText(_translate("Dialog", "Tambahkan Tanaman"))
        self.deskripsiLabel.setText(_translate("Dialog", "Deskripsi"))
        self.hargaLabel.setText(_translate("Dialog", "Harga Tanaman"))
        self.domisiliLabel.setText(_translate("Dialog", "Domisili Tanaman"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_addTanaman()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
