# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listTanaman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class UI_listTanaman(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setAutoFillBackground(False)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: white;}")
        self.bgwidget.setObjectName("bgwidget")

        # Gambar 1
        self.gambar1 = QtWidgets.QLabel(self.bgwidget)
        self.gambar1.setGeometry(QtCore.QRect(100, 150, 240, 240))
        self.gambar1.setText("")
        self.gambar1.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambar1.setScaledContents(True)
        self.gambar1.setObjectName("gambar1")

        # Gambar 2
        self.gambar2 = QtWidgets.QLabel(self.bgwidget)
        self.gambar2.setGeometry(QtCore.QRect(480, 150, 240, 240))
        self.gambar2.setText("")
        self.gambar2.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambar2.setScaledContents(True)
        self.gambar2.setObjectName("gambar2")

        # Gambar 3
        self.gambar3 = QtWidgets.QLabel(self.bgwidget)
        self.gambar3.setGeometry(QtCore.QRect(850, 150, 240, 240))
        self.gambar3.setText("")
        self.gambar3.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambar3.setScaledContents(True)
        self.gambar3.setObjectName("gambar3")

        # Gambar 4
        self.gambar4 = QtWidgets.QLabel(self.bgwidget)
        self.gambar4.setGeometry(QtCore.QRect(100, 460, 240, 240))
        self.gambar4.setText("")
        self.gambar4.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambar4.setScaledContents(True)
        self.gambar4.setObjectName("gambar4")

        # Gambar 5
        self.gambar5 = QtWidgets.QLabel(self.bgwidget)
        self.gambar5.setGeometry(QtCore.QRect(480, 460, 240, 240))
        self.gambar5.setText("")
        self.gambar5.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambar5.setScaledContents(True)
        self.gambar5.setObjectName("gambar5")

        # Gambar 6
        self.gambar6 = QtWidgets.QLabel(self.bgwidget)
        self.gambar6.setGeometry(QtCore.QRect(850, 460, 240, 240))
        self.gambar6.setText("")
        self.gambar6.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambar6.setScaledContents(True)
        self.gambar6.setObjectName("gambar6")

        # Label 1
        self.label1 = QtWidgets.QLabel(self.bgwidget)
        self.label1.setGeometry(QtCore.QRect(100, 400, 241, 31))
        self.label1.setStyleSheet("font: 16pt \"Sansita\";")
        self.label1.setObjectName("label1")
        self.label1.setAlignment(Qt.AlignCenter)

        # Label 2
        self.label2 = QtWidgets.QLabel(self.bgwidget)
        self.label2.setGeometry(QtCore.QRect(480, 400, 241, 31))
        self.label2.setStyleSheet("font: 16pt \"Sansita\";")
        self.label2.setObjectName("label2")
        self.label2.setAlignment(Qt.AlignCenter)

        # Label 3
        self.label3 = QtWidgets.QLabel(self.bgwidget)
        self.label3.setGeometry(QtCore.QRect(850, 400, 241, 31))
        self.label3.setStyleSheet("font: 16pt \"Sansita\";")
        self.label3.setObjectName("label3")
        self.label3.setAlignment(Qt.AlignCenter)

        # Label 4
        self.label4 = QtWidgets.QLabel(self.bgwidget)
        self.label4.setGeometry(QtCore.QRect(100, 710, 241, 31))
        self.label4.setStyleSheet("font: 16pt \"Sansita\";")
        self.label4.setObjectName("label4")
        self.label4.setAlignment(Qt.AlignCenter)

        # Label 5
        self.label5 = QtWidgets.QLabel(self.bgwidget)
        self.label5.setGeometry(QtCore.QRect(480, 710, 241, 31))
        self.label5.setStyleSheet("font: 16pt \"Sansita\";")
        self.label5.setObjectName("label5")
        self.label5.setAlignment(Qt.AlignCenter)

        # Label 6
        self.label6 = QtWidgets.QLabel(self.bgwidget)
        self.label6.setGeometry(QtCore.QRect(850, 710, 241, 31))
        self.label6.setStyleSheet("font: 16pt \"Sansita\";")
        self.label6.setObjectName("label6")
        self.label6.setAlignment(Qt.AlignCenter)

        # Navigation bar
        # TODO : ganti navbar
        self.navbar = QtWidgets.QFrame(self.bgwidget)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 1211, 91))
        self.navbar.setStyleSheet("QFrame#navbar{\n"
"    background-color: rgb(234, 216, 202);\n"
"   \n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.frame_3 = QtWidgets.QFrame(self.navbar)
        self.frame_3.setGeometry(QtCore.QRect(-10, -30, 1211, 51))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(136, 179, 160);\n"
"   \n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Logo_2 = QtWidgets.QLabel(self.navbar)
        self.Logo_2.setGeometry(QtCore.QRect(0, 0, 281, 121))
        self.Logo_2.setStyleSheet("font: 87 26pt \"Sansita\";\n"
"color : rgb(0, 0, 0) ")
        self.Logo_2.setText("")
        self.Logo_2.setPixmap(QtGui.QPixmap("././img/logo.png"))
        self.Logo_2.setScaledContents(True)
        self.Logo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_2.setObjectName("Logo_2")
        self.berandaButton = QtWidgets.QPushButton(self.navbar)
        self.berandaButton.setGeometry(QtCore.QRect(350, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.berandaButton.setFont(font)
        self.berandaButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.berandaButton.setCheckable(False)
        self.berandaButton.setObjectName("berandaButton")
        self.tanamanButton = QtWidgets.QPushButton(self.navbar)
        self.tanamanButton.setGeometry(QtCore.QRect(520, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.tanamanButton.setFont(font)
        self.tanamanButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color :  rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.tanamanButton.setCheckable(False)
        self.tanamanButton.setObjectName("tanamanButton")
        self.aboutButton = QtWidgets.QPushButton(self.navbar)
        self.aboutButton.setGeometry(QtCore.QRect(670, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.aboutButton.setCheckable(False)
        self.aboutButton.setObjectName("aboutButton")
        self.search = QtWidgets.QLabel(self.navbar)
        self.search.setGeometry(QtCore.QRect(930, 40, 31, 31))
        self.search.setText("")
        self.search.setPixmap(QtGui.QPixmap("././img/Search.png"))
        self.search.setScaledContents(True)
        self.search.setObjectName("search")
        self.account = QtWidgets.QLabel(self.navbar)
        self.account.setGeometry(QtCore.QRect(980, 35, 31, 41))
        self.account.setText("")
        self.account.setPixmap(QtGui.QPixmap("././img/User.png"))
        self.account.setScaledContents(True)
        self.account.setObjectName("account")
        self.notification = QtWidgets.QLabel(self.navbar)
        self.notification.setGeometry(QtCore.QRect(1030, 40, 31, 31))
        self.notification.setText("")
        self.notification.setPixmap(QtGui.QPixmap("././img/Doorbell.png"))
        self.notification.setScaledContents(True)
        self.notification.setObjectName("notification")
        self.keranjang = QtWidgets.QLabel(self.navbar)
        self.keranjang.setGeometry(QtCore.QRect(1080, 30, 31, 51))
        self.keranjang.setText("")
        self.keranjang.setPixmap(QtGui.QPixmap("././img/Shopping Cart.png"))
        self.keranjang.setScaledContents(True)
        self.keranjang.setObjectName("keranjang")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label1.setText(_translate("Dialog", "Nama Tanaman 1"))
        self.label2.setText(_translate("Dialog", "Nama Tanaman 2"))
        self.label3.setText(_translate("Dialog", "Nama Tanaman 3"))
        self.label4.setText(_translate("Dialog", "Nama Tanaman 4"))
        self.label5.setText(_translate("Dialog", "Nama Tanaman 5"))
        self.label6.setText(_translate("Dialog", "Nama Tanaman 6"))
        self.berandaButton.setText(_translate("Dialog", "Beranda"))
        self.tanamanButton.setText(_translate("Dialog", "Tanaman"))
        self.aboutButton.setText(_translate("Dialog", "Tentang Kami"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_listTanaman()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
