# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/modalItemKeranjang.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 142)
        Form.setMinimumSize(QtCore.QSize(400, 120))
        Form.setMaximumSize(QtCore.QSize(16777215, 142))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(400, 120))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_3.setStyleSheet("position: absolute;\n"
"width: 236px;\n"
"height: 24px;\n"
"left: 144px;\n"
"top: 228px;\n"
"\n"
"font-family: \'Sansita\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 17px;\n"
"line-height: 24px;\n"
"/* identical to box height */\n"
"\n"
"color: #000000;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.noItem = QtWidgets.QLabel(self.widget_3)
        self.noItem.setMinimumSize(QtCore.QSize(40, 0))
        self.noItem.setMaximumSize(QtCore.QSize(40, 16777215))
        self.noItem.setStyleSheet("")
        self.noItem.setObjectName("noItem")
        self.horizontalLayout.addWidget(self.noItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.namaItem = QtWidgets.QLabel(self.widget_3)
        self.namaItem.setObjectName("namaItem")
        self.verticalLayout_5.addWidget(self.namaItem)
        self.jumlah = QtWidgets.QLabel(self.widget_3)
        self.jumlah.setObjectName("jumlah")
        self.verticalLayout_5.addWidget(self.jumlah)
        self.tanggalSewa = QtWidgets.QLabel(self.widget_3)
        self.tanggalSewa.setObjectName("tanggalSewa")
        self.verticalLayout_5.addWidget(self.tanggalSewa)
        self.tanggalKembali = QtWidgets.QLabel(self.widget_3)
        self.tanggalKembali.setObjectName("tanggalKembali")
        self.verticalLayout_5.addWidget(self.tanggalKembali)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.hargaTotal = QtWidgets.QLabel(self.widget_3)
        self.hargaTotal.setMinimumSize(QtCore.QSize(300, 0))
        self.hargaTotal.setMaximumSize(QtCore.QSize(300, 16777215))
        self.hargaTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hargaTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hargaTotal.setObjectName("hargaTotal")
        self.horizontalLayout.addWidget(self.hargaTotal)
        self.trash = QtWidgets.QPushButton(self.widget_3)
        self.trash.setMinimumSize(QtCore.QSize(31, 31))
        self.trash.setMaximumSize(QtCore.QSize(31, 31))
        self.trash.setStyleSheet("background:transparent;")
        self.trash.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\../../img/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trash.setIcon(icon)
        self.trash.setIconSize(QtCore.QSize(31, 31))
        self.trash.setObjectName("trash")
        self.horizontalLayout.addWidget(self.trash)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.noItem.setText(_translate("Form", "no"))
        self.namaItem.setText(_translate("Form", "Nama Item"))
        self.jumlah.setText(_translate("Form", "Jumlah"))
        self.tanggalSewa.setText(_translate("Form", "Tanggal Sewa"))
        self.tanggalKembali.setText(_translate("Form", "Tanggal Pengembalian"))
        self.hargaTotal.setText(_translate("Form", "Harga Total"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
