# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addTanaman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

data = [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola','Antigua & Deps',
    'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia Herzegovina', 'Botswana',
    'Brazil', 'Brunei', 'Bulgaria', 'Burkina', 'Burundi', 'Cambodia', 'Cameroon',
    'Canada', 'Cape Verde', 'Central African Rep', 'Chad', 'Chile', 'China',
    'Colombia', 'Comoros', 'Congo', 'Congo {Democratic Rep}', 'Costa Rica',
    'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti',
    'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
    'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
    'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
    'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
    'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
    'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica',
    'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea North',
    'Korea South', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
    'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
    'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
    'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
    'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
    'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 
    'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan',
    'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
    'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda',
    'St Kitts & Nevis', 'St Lucia', 'Saint Vincent & the Grenadines',
    'Samoa', 'San Marino', 'Sao Tome & Principe', 'Saudi Arabia', 'Senegal',
    'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
    'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain',
    'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland',
    'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
    'Trinidad & Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda',
    'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
    'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
    'Yemen', 'Zambia', 'Zimbabwe'
    ]

class UI_addTanaman(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMouseTracking(False)
        self.bgwidget.setAutoFillBackground(False)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: white;}")
        self.bgwidget.setObjectName("bgwidget")

        # BAGIAN NAVBAR
        # TODO : Ganti sama navbar yang bener
        self.navbar = QtWidgets.QFrame(self.bgwidget)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 1211, 91))
        self.navbar.setStyleSheet("QFrame#navbar{\n"
                                  "    background-color: rgb(234, 216, 202);\n"
                                  "   \n"
                                  "    border-style: outset;\n"
                                  "    padding: 5px;\n"
                                  "}")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.frame_2 = QtWidgets.QFrame(self.navbar)
        self.frame_2.setGeometry(QtCore.QRect(-10, -30, 1211, 51))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
                                   "    background-color: rgb(136, 179, 160);\n"
                                   "   \n"
                                   "    border-style: outset;\n"
                                   "    padding: 5px;\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Logo = QtWidgets.QLabel(self.navbar)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 281, 121))
        self.Logo.setStyleSheet("font: 87 26pt \"Sansita\";\n"
                                "color : rgb(0, 0, 0) ")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("././img/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.berandaButton = QtWidgets.QPushButton(self.navbar)
        self.berandaButton.setGeometry(QtCore.QRect(350, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.berandaButton.setFont(font)
        self.berandaButton.setAutoFillBackground(False)
        self.berandaButton.setStyleSheet("QPushButton {\n"
                                         "    border: 0px solid #555;\n"
                                         "    border-radius: 15px;\n"
                                         "    border-style: outset;\n"
                                         "    padding: 5px;\n"
                                         "    color : rgb(53, 78, 59);\n"
                                         "    background-color :  rgb(234, 216, 202);\n"
                                         "    }\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    color : white;\n"
                                         "    }")
        self.berandaButton.setCheckable(False)
        self.berandaButton.setObjectName("berandaButton")
        self.tanamanButton = QtWidgets.QPushButton(self.navbar)
        self.tanamanButton.setGeometry(QtCore.QRect(520, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.tanamanButton.setFont(font)
        self.tanamanButton.setStyleSheet("QPushButton {\n"
                                         "    border: 0px solid #555;\n"
                                         "    border-radius: 15px;\n"
                                         "    border-style: outset;\n"
                                         "    padding: 5px;\n"
                                         "    color :  rgb(53, 78, 59);\n"
                                         "    background-color :  rgb(234, 216, 202);\n"
                                         "    }\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    color : white;\n"
                                         "    }")
        self.tanamanButton.setCheckable(False)
        self.tanamanButton.setObjectName("tanamanButton")
        self.aboutButton = QtWidgets.QPushButton(self.navbar)
        self.aboutButton.setGeometry(QtCore.QRect(670, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("QPushButton {\n"
                                       "    border: 0px solid #555;\n"
                                       "    border-radius: 15px;\n"
                                       "    border-style: outset;\n"
                                       "    padding: 5px;\n"
                                       "    color : rgb(53, 78, 59);\n"
                                       "    background-color :  rgb(234, 216, 202);\n"
                                       "    }\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    color : white;\n"
                                       "    }")
        self.aboutButton.setCheckable(False)
        self.aboutButton.setObjectName("aboutButton")
        self.searchButton = QtWidgets.QPushButton(self.navbar)
        self.searchButton.setGeometry(QtCore.QRect(930, 40, 31, 31))
        self.searchButton.setMouseTracking(False)
        self.searchButton.setAutoFillBackground(False)
        self.searchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("././img/Search.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setIconSize(QtCore.QSize(31, 31))
        self.searchButton.setAutoDefault(True)
        self.searchButton.setDefault(False)
        self.searchButton.setFlat(True)
        self.searchButton.setObjectName("searchButton")
        self.userButton = QtWidgets.QPushButton(self.navbar)
        self.userButton.setGeometry(QtCore.QRect(980, 35, 31, 41))
        self.userButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("././img/User.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userButton.setIcon(icon1)
        self.userButton.setIconSize(QtCore.QSize(31, 41))
        self.userButton.setFlat(True)
        self.userButton.setObjectName("userButton")
        self.cartButton = QtWidgets.QPushButton(self.navbar)
        self.cartButton.setGeometry(QtCore.QRect(1080, 30, 31, 51))
        self.cartButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("././img/Shopping Cart.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("././img/Shopping Cart.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cartButton.setIcon(icon2)
        self.cartButton.setIconSize(QtCore.QSize(31, 51))
        self.cartButton.setAutoExclusive(False)
        self.cartButton.setAutoDefault(True)
        self.cartButton.setFlat(True)
        self.cartButton.setObjectName("cartButton")
        self.notification = QtWidgets.QLabel(self.navbar)
        self.notification.setGeometry(QtCore.QRect(1030, 40, 31, 31))
        self.notification.setText("")
        self.notification.setPixmap(QtGui.QPixmap("././img/Doorbell.png"))
        self.notification.setScaledContents(True)
        self.notification.setObjectName("notification")

        # Label Nama Tanaman
        self.namaTanamanLabel = QtWidgets.QLabel(self.bgwidget)
        self.namaTanamanLabel.setGeometry(QtCore.QRect(40, 120, 188, 33))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.namaTanamanLabel.setFont(font)
        self.namaTanamanLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.namaTanamanLabel.setObjectName("namaTanamanLabel")
        
        # Label Upload Foto
        self.uploadFotoLabel = QtWidgets.QLabel(self.bgwidget)
        self.uploadFotoLabel.setGeometry(QtCore.QRect(40, 190, 161, 31))
        self.uploadFotoLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.uploadFotoLabel.setObjectName("uploadFotoLabel")
        
        # Label Stok
        self.stokLabel = QtWidgets.QLabel(self.bgwidget)
        self.stokLabel.setGeometry(QtCore.QRect(40, 450, 171, 33))
        self.stokLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.stokLabel.setObjectName("stokLabel")

        # Label Domisili
        self.domisiliLabel = QtWidgets.QLabel(self.bgwidget)
        self.domisiliLabel.setGeometry(QtCore.QRect(310, 260, 751, 151))
        self.domisiliLabel.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;")
        self.domisiliLabel.setText("")
        self.domisiliLabel.setObjectName("domisiliLabel")
        
        # Button Tambahkan Tanaman
        self.tambahkanTanamanButton = QtWidgets.QPushButton(self.bgwidget)
        self.tambahkanTanamanButton.setGeometry(QtCore.QRect(500, 700, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        self.tambahkanTanamanButton.setFont(font)
        self.tambahkanTanamanButton.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"     background-color : rgb(85, 170, 127);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.tambahkanTanamanButton.setCheckable(False)
        self.tambahkanTanamanButton.setObjectName("tambahkanTanamanButton")

        # Label Deskripsi
        self.deskripsiLabel = QtWidgets.QLabel(self.bgwidget)
        self.deskripsiLabel.setGeometry(QtCore.QRect(40, 260, 161, 31))
        self.deskripsiLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.deskripsiLabel.setObjectName("deskripsiLabel")

        # Label Harga
        self.hargaLabel = QtWidgets.QLabel(self.bgwidget)
        self.hargaLabel.setGeometry(QtCore.QRect(40, 520, 190, 33))
        self.hargaLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.hargaLabel.setObjectName("hargaLabel")

        # Label domisili
        self.domisiliLabel = QtWidgets.QLabel(self.bgwidget)
        self.domisiliLabel.setGeometry(QtCore.QRect(40, 590, 211, 33))
        self.domisiliLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.domisiliLabel.setObjectName("domisiliLabel")

        # Button Upload Foto
        self.uploadFotoButton = QtWidgets.QPushButton(self.bgwidget)
        self.uploadFotoButton.setGeometry(QtCore.QRect(610, 190, 51, 41))
        self.uploadFotoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("././img/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadFotoButton.setIcon(icon)
        self.uploadFotoButton.setIconSize(QtCore.QSize(40, 40))
        self.uploadFotoButton.setFlat(True)
        self.uploadFotoButton.setObjectName("uploadFotoButton")

        # Line Edit Upload Foto
        # TODO : Ambil path file dari uploadFotoButton
        self.uploadFotoEdit = QtWidgets.QLabel(self.bgwidget)
        self.uploadFotoEdit.setGeometry(QtCore.QRect(310, 190, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.uploadFotoEdit.setFont(font)
        self.uploadFotoEdit.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : #769D8A;\n"
"    padding: 5px;")
        self.uploadFotoEdit.setText("Path to File")
        self.uploadFotoEdit.setObjectName("uploadFotoEdit")
        
        # Text Edit Deskripsi
        # TODO : sesuain textedit kayak lineedit
        self.textEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 260, 751, 151))
        self.textEdit.setObjectName("textEdit")
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color : #769D8A;")

        # Line Edit Nama
        self.namaTanamanEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.namaTanamanEdit.setGeometry(QtCore.QRect(310, 120, 301, 41))
        self.namaTanamanEdit.setStyleSheet("QLineEdit#namaTanamanEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.namaTanamanEdit.setText("")
        self.namaTanamanEdit.setObjectName("namaTanamanEdit")
        
        # Line Edit Stok
        self.stokEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.stokEdit.setGeometry(QtCore.QRect(310, 450, 211, 41))
        self.stokEdit.setStyleSheet("QLineEdit#stokEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.stokEdit.setText("")
        self.onlyInt = QtGui.QIntValidator()
        self.stokEdit.setValidator(self.onlyInt)
        self.stokEdit.setObjectName("stokEdit")

        # Line Edit Harga
        self.hargaEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.hargaEdit.setGeometry(QtCore.QRect(310, 520, 211, 41))
        self.hargaEdit.setStyleSheet("QLineEdit#hargaEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.hargaEdit.setText("")
        self.hargaEdit.setValidator(self.onlyInt)
        self.hargaEdit.setObjectName("hargaEdit")

        # Line Edit Domisili
        self.domisiliEdit = QtWidgets.QLineEdit(self.bgwidget)
        self.domisiliEdit.setGeometry(QtCore.QRect(310, 590, 211, 41))
        self.domisiliEdit.setStyleSheet("QLineEdit#domisiliEdit{\n"
"    background-color: #769D8A;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.domisiliEdit.setText("")
        completer = QtWidgets.QCompleter(data)
        self.domisiliEdit.setCompleter(completer)
        self.domisiliEdit.setObjectName("domisiliEdit")

        self.domisiliEdit.raise_()
        self.hargaEdit.raise_()
        self.stokEdit.raise_()
        self.namaTanamanEdit.raise_()
        self.navbar.raise_()
        self.namaTanamanLabel.raise_()
        self.uploadFotoLabel.raise_()
        self.stokLabel.raise_()
        self.domisiliLabel.raise_()
        self.tambahkanTanamanButton.raise_()
        self.deskripsiLabel.raise_()
        self.hargaLabel.raise_()
        self.domisiliLabel.raise_()
        self.uploadFotoButton.raise_()
        self.textEdit.raise_()
        self.uploadFotoEdit.raise_()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def pushButton_handler(self):
        print("Button pressed")
        self.open_dialog_box()

    # TODO : save pathnya lempar ke label
    def open_dialog_box(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        path = filename[0]
        self.uploadFotoEdit.setText(path)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.berandaButton.setText(_translate("Dialog", "Beranda"))
        self.tanamanButton.setText(_translate("Dialog", "Tanaman"))
        self.aboutButton.setText(_translate("Dialog", "Tentang Kami"))
        self.namaTanamanLabel.setText(_translate("Dialog", "Nama Tanaman"))
        self.uploadFotoLabel.setText(_translate("Dialog", "Upload Foto"))
        self.uploadFotoButton.clicked.connect(self.pushButton_handler)
        self.stokLabel.setText(_translate("Dialog", "Stok Tanaman"))
        self.tambahkanTanamanButton.setText(_translate("Dialog", "Tambahkan Tanaman"))
        self.deskripsiLabel.setText(_translate("Dialog", "Deskripsi"))
        self.hargaLabel.setText(_translate("Dialog", "Harga Tanaman"))
        self.domisiliLabel.setText(_translate("Dialog", "Domisili Tanaman"))
    
    def __init__(self):
        super(QtWidgets.QWidget, self).__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_addTanaman()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
