# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailTanaman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class UI_detailTanaman(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setAutoFillBackground(False)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: white;}")
        self.bgwidget.setObjectName("bgwidget")

        # Navigation bar
        self.navbar = QtWidgets.QFrame(self.bgwidget)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 1211, 91))
        self.navbar.setStyleSheet("QFrame#navbar{\n"
                                  "    background-color: rgb(234, 216, 202);\n"
                                  "   \n"
                                  "    border-style: outset;\n"
                                  "    padding: 5px;\n"
                                  "}")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.frame_2 = QtWidgets.QFrame(self.navbar)
        self.frame_2.setGeometry(QtCore.QRect(-10, -30, 1211, 51))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
                                   "    background-color: rgb(136, 179, 160);\n"
                                   "   \n"
                                   "    border-style: outset;\n"
                                   "    padding: 5px;\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Logo = QtWidgets.QLabel(self.navbar)
        self.Logo.setGeometry(QtCore.QRect(0, 0, 281, 121))
        self.Logo.setStyleSheet("font: 87 26pt \"Sansita\";\n"
                                "color : rgb(0, 0, 0) ")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("././img/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.berandaButton = QtWidgets.QPushButton(self.navbar)
        self.berandaButton.setGeometry(QtCore.QRect(350, 35, 95, 40))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.berandaButton.setFont(font)
        self.berandaButton.setAutoFillBackground(False)
        self.berandaButton.setStyleSheet("QPushButton {\n"
                                         "    border: 0px solid #555;\n"
                                         "    border-radius: 15px;\n"
                                         "    border-style: outset;\n"
                                         "    padding: 5px;\n"
                                         "    color : rgb(53, 78, 59);\n"
                                         "    background-color :  rgb(234, 216, 202);\n"
                                         "    }\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    color : white;\n"
                                         "    }")
        self.berandaButton.setCheckable(False)
        self.berandaButton.setObjectName("berandaButton")
        self.tanamanButton = QtWidgets.QPushButton(self.navbar)
        self.tanamanButton.setGeometry(QtCore.QRect(525, 35, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.tanamanButton.setFont(font)
        self.tanamanButton.setStyleSheet("QPushButton {\n"
                                         "    border: 0px solid #555;\n"
                                         "    border-radius: 15px;\n"
                                         "    border-style: outset;\n"
                                         "    padding: 5px;\n"
                                         "    color :  rgb(53, 78, 59);\n"
                                         "    background-color :  rgb(234, 216, 202);\n"
                                         "    }\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    color : white;\n"
                                         "    }")
        self.tanamanButton.setCheckable(False)
        self.tanamanButton.setObjectName("tanamanButton")
        self.aboutButton = QtWidgets.QPushButton(self.navbar)
        self.aboutButton.setGeometry(QtCore.QRect(710, 35, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("QPushButton {\n"
                                       "    border: 0px solid #555;\n"
                                       "    border-radius: 15px;\n"
                                       "    border-style: outset;\n"
                                       "    padding: 5px;\n"
                                       "    color : rgb(53, 78, 59);\n"
                                       "    background-color :  rgb(234, 216, 202);\n"
                                       "    }\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    color : white;\n"
                                       "    }")
        self.aboutButton.setCheckable(False)
        self.aboutButton.setObjectName("aboutButton")
        self.searchButton = QtWidgets.QPushButton(self.navbar)
        self.searchButton.setGeometry(QtCore.QRect(980, 40, 31, 31))
        self.searchButton.setMouseTracking(False)
        self.searchButton.setAutoFillBackground(False)
        self.searchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("././img/Search.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setIconSize(QtCore.QSize(31, 31))
        self.searchButton.setAutoDefault(True)
        self.searchButton.setDefault(False)
        self.searchButton.setFlat(True)
        self.searchButton.setObjectName("searchButton")
        self.userButton = QtWidgets.QPushButton(self.navbar)
        self.userButton.setGeometry(QtCore.QRect(1030, 35, 31, 41))
        self.userButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("././img/User.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userButton.setIcon(icon1)
        self.userButton.setIconSize(QtCore.QSize(31, 41))
        self.userButton.setFlat(True)
        self.userButton.setObjectName("userButton")
        self.notification = QtWidgets.QLabel(self.navbar)
        self.notification.setGeometry(QtCore.QRect(1080, 40, 31, 31))
        self.notification.setText("")
        self.notification.setPixmap(QtGui.QPixmap("././img/Doorbell.png"))
        self.notification.setScaledContents(True)
        self.notification.setObjectName("notification")
        self.cartButton = QtWidgets.QPushButton(self.navbar)
        self.cartButton.setGeometry(QtCore.QRect(1130, 30, 31, 51))
        self.cartButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("././img/Shopping Cart.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("././img/Shopping Cart.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cartButton.setIcon(icon2)
        self.cartButton.setIconSize(QtCore.QSize(31, 51))
        self.cartButton.setAutoExclusive(False)
        self.cartButton.setAutoDefault(True)
        self.cartButton.setFlat(True)
        self.cartButton.setObjectName("cartButton")

        # Gambar Tanaman
        self.gambarTanaman = QtWidgets.QLabel(self.bgwidget)
        self.gambarTanaman.setGeometry(QtCore.QRect(80, 190, 231, 231))
        self.gambarTanaman.setText("")
        self.gambarTanaman.setPixmap(QtGui.QPixmap("././img/placeholderPlant.png"))
        self.gambarTanaman.setScaledContents(True)
        self.gambarTanaman.setObjectName("gambarTanaman")

        # Nama Tanaman
        self.namaLabel = QtWidgets.QLabel(self.bgwidget)
        self.namaLabel.setGeometry(QtCore.QRect(80, 140, 500, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.namaLabel.setFont(font)
        self.namaLabel.setStyleSheet("font: 22pt \"Sansita\";")
        self.namaLabel.setObjectName("namaLabel")

        # Deskripsi Tanaman
        self.deskripsiLabel = QtWidgets.QLabel(self.bgwidget)
        self.deskripsiLabel.setGeometry(QtCore.QRect(360, 190, 571, 181))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.deskripsiLabel.setFont(font)
        self.deskripsiLabel.setStyleSheet("font: 12pt \"Sansita\";")
        self.deskripsiLabel.setScaledContents(False)
        self.deskripsiLabel.setWordWrap(True)
        self.deskripsiLabel.setObjectName("deskripsiLabel")

        # Label Stok
        self.stokLabel = QtWidgets.QLabel(self.bgwidget)
        self.stokLabel.setGeometry(QtCore.QRect(360, 420, 161, 31))
        self.stokLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.stokLabel.setObjectName("stokLabel")

        # Label Harga
        self.hargaLabel = QtWidgets.QLabel(self.bgwidget)
        self.hargaLabel.setGeometry(QtCore.QRect(360, 460, 207, 34))
        self.hargaLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.hargaLabel.setObjectName("hargaLabel")

        # Label Domisili
        self.domisiliLabel = QtWidgets.QLabel(self.bgwidget)
        self.domisiliLabel.setGeometry(QtCore.QRect(360, 500, 211, 34))
        self.domisiliLabel.setStyleSheet("font: 16pt \"Sansita\";")
        self.domisiliLabel.setObjectName("domisiliLabel")

        # Text Stok
        self.stokText = QtWidgets.QLabel(self.bgwidget)
        self.stokText.setGeometry(QtCore.QRect(580, 420, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.stokText.setFont(font)
        self.stokText.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;")
        self.stokText.setText("Stok")
        self.stokText.setAlignment(QtCore.Qt.AlignCenter)
        self.stokText.setObjectName("stokText")

        # Text Harga
        self.hargaText = QtWidgets.QLabel(self.bgwidget)
        self.hargaText.setGeometry(QtCore.QRect(580, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.hargaText.setFont(font)
        self.hargaText.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;")
        self.hargaText.setText("Hrg")
        self.hargaText.setAlignment(QtCore.Qt.AlignCenter)
        self.hargaText.setObjectName("hargaText")

        # Text Domisili
        self.domisiliText = QtWidgets.QLabel(self.bgwidget)
        self.domisiliText.setGeometry(QtCore.QRect(580, 500, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        self.domisiliText.setFont(font)
        self.domisiliText.setStyleSheet(" border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;")
        self.domisiliText.setText("Dom")
        self.domisiliText.setAlignment(QtCore.Qt.AlignCenter)
        self.domisiliText.setObjectName("domisiliText")

        # Frame Sewa
        self.frameSewa = QtWidgets.QFrame(self.bgwidget)
        self.frameSewa.setGeometry(QtCore.QRect(150, 590, 891, 151))
        self.frameSewa.setStyleSheet(
"    background-color: rgb(226, 234, 213);\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
";")
        self.frameSewa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSewa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSewa.setObjectName("frameSewa")

        # Button Tambahkan Ke Keranjang
        self.tambahkanKeKeranjangButton = QtWidgets.QPushButton(self.frameSewa)
        self.tambahkanKeKeranjangButton.setGeometry(QtCore.QRect(330, 110, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        self.tambahkanKeKeranjangButton.setFont(font)
        self.tambahkanKeKeranjangButton.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 0px solid #555;\n"
"    border-radius: 8px;\n"
"    border-style: outset;\n"
"    background-color : rgb(136, 179, 160);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"     background-color : rgb(85, 170, 127);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.tambahkanKeKeranjangButton.setCheckable(False)
        self.tambahkanKeKeranjangButton.setObjectName("tambahkanKeKeranjangButton")
        
        # Label Jumlah
        self.jumlahLabel = QtWidgets.QLabel(self.frameSewa)
        self.jumlahLabel.setGeometry(QtCore.QRect(62, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.jumlahLabel.setFont(font)
        self.jumlahLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.jumlahLabel.setObjectName("jumlahLabel")

        # Label Text Jumlah
        self.jumlahText = QtWidgets.QLineEdit(self.frameSewa)
        self.jumlahText.setGeometry(QtCore.QRect(62, 50, 71, 41))
        self.jumlahText.setStyleSheet(
"    background-color: white;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
";")
        self.jumlahText.setText("")
        self.jumlahText.setMaxLength(3)
        self.onlyInt = QtGui.QIntValidator()
        self.jumlahText.setValidator(self.onlyInt)
        self.jumlahText.setObjectName("jumlahText")

        # Label Mulai Sewa
        self.mulaiSewaLabel = QtWidgets.QLabel(self.frameSewa)
        self.mulaiSewaLabel.setGeometry(QtCore.QRect(195, 20, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mulaiSewaLabel.setFont(font)
        self.mulaiSewaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mulaiSewaLabel.setObjectName("mulaiSewaLabel")

        # Date mulai sewa
        self.mulaiSewaDate = QtWidgets.QDateEdit(self.frameSewa)
        self.mulaiSewaDate.setGeometry(QtCore.QRect(195, 50, 180, 41))
        self.mulaiSewaDate.setStyleSheet(
"    background-color: white;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
";")    
        self.mulaiSewaDate.setAlignment(QtCore.Qt.AlignCenter)
        self.mulaiSewaDate.setObjectName("mulaiSewaDate")

        # Label Kembali Sewa
        self.kembaliSewaLabel = QtWidgets.QLabel(self.frameSewa)
        self.kembaliSewaLabel.setGeometry(QtCore.QRect(437, 20, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.kembaliSewaLabel.setFont(font)
        self.kembaliSewaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kembaliSewaLabel.setObjectName("kembaliSewaLabel")

        # Date kembali sewa
        self.kembaliSewaDate = QtWidgets.QDateEdit(self.frameSewa)
        self.kembaliSewaDate.setGeometry(QtCore.QRect(437, 50, 180, 41))
        self.kembaliSewaDate.setStyleSheet(
"    background-color: white;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
";")    
        self.kembaliSewaDate.setAlignment(QtCore.Qt.AlignCenter)
        self.kembaliSewaDate.setObjectName("kembaliSewaDate")

        # Label Total Harga
        self.totalHargaLabel = QtWidgets.QLabel(self.frameSewa)
        self.totalHargaLabel.setGeometry(QtCore.QRect(679, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.totalHargaLabel.setFont(font)
        self.totalHargaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalHargaLabel.setObjectName("totalHargaLabel")

        # Label Text Total Harga
        self.totalHargaText = QtWidgets.QLabel(self.frameSewa)
        self.totalHargaText.setGeometry(QtCore.QRect(679, 50, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.totalHargaText.setFont(font)
        self.totalHargaText.setStyleSheet(
"    background-color: white;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
";")
        self.totalHargaText.setText("hrga")
        self.totalHargaText.setObjectName("totalHargaText")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.berandaButton.setText(_translate("Dialog", "Beranda"))
        self.tanamanButton.setText(_translate("Dialog", "Tanaman"))
        self.aboutButton.setText(_translate("Dialog", "Tentang Kami"))
        self.namaLabel.setText(_translate("Dialog", "Nama Tanaman"))
        self.deskripsiLabel.setText(_translate("Dialog", "\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\""))
        self.stokLabel.setText(_translate("Dialog", "Stok Tanaman"))
        self.hargaLabel.setText(_translate("Dialog", "Harga Tanaman"))
        self.domisiliLabel.setText(_translate("Dialog", "Domisili Tanaman"))
        self.tambahkanKeKeranjangButton.setText(_translate("Dialog", "Tambahkan Ke Keranjang"))
        self.jumlahLabel.setText(_translate("Dialog", "Jumlah"))
        self.mulaiSewaLabel.setText(_translate("Dialog", "Tanggal Mulai Sewa"))
        self.kembaliSewaLabel.setText(_translate("Dialog", "Tanggal Pengembalian"))
        self.totalHargaLabel.setText(_translate("Dialog", "Total Harga"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_detailTanaman()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
