# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greetingAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):

    def __init__(self):
        super(QtWidgets.QWidget, self).__init__()
        self.setupUi(self)
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(319, 200)
        Form.setMinimumSize(QtCore.QSize(0, 200))
        Form.setMaximumSize(QtCore.QSize(16777215, 300))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("background: #B1B6AF;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 28, 299, 20))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("font-family: \'Sansita\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"color: rgb(64,64,64);\n"
"\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.keluarButton = QtWidgets.QPushButton(self.frame_2)
        self.keluarButton.setGeometry(QtCore.QRect(20, 140, 273, 50))
        self.keluarButton.setMinimumSize(QtCore.QSize(0, 50))
        self.keluarButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.keluarButton.setStyleSheet("/* Frame 4 */\n"
"QPushButton {\n"
"position: absolute;\n"
"width: 351px;\n"
"height: 45px;\n"
"left: 1014px;\n"
"top: 976px;\n"
"\n"
"background: #769D8A;\n"
"border-radius: 8px;\n"
"\n"
"\n"
"/* Konfirmasi Pengajuan Penyewaan */\n"
"\n"
"position: absolute;\n"
"width: 273px;\n"
"height: 24px;\n"
"left: 39px;\n"
"top: 11px;\n"
"\n"
"font-family: \'Sansita\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"/* identical to box height */\n"
"\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color : black;\n"
"}\n"
"")
        self.keluarButton.setObjectName("keluarButton")
        self.masukAdminButton = QtWidgets.QPushButton(self.frame_2)
        self.masukAdminButton.setGeometry(QtCore.QRect(20, 70, 273, 50))
        self.masukAdminButton.setStyleSheet("/* Frame 4 */\n"
"QPushButton {\n"
"position: absolute;\n"
"width: 351px;\n"
"height: 45px;\n"
"left: 1014px;\n"
"top: 976px;\n"
"\n"
"background: #769D8A;\n"
"border-radius: 8px;\n"
"\n"
"\n"
"/* Konfirmasi Pengajuan Penyewaan */\n"
"\n"
"position: absolute;\n"
"width: 273px;\n"
"height: 24px;\n"
"left: 39px;\n"
"top: 11px;\n"
"\n"
"font-family: \'Sansita\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 20px;\n"
"line-height: 24px;\n"
"/* identical to box height */\n"
"\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color : black;\n"
"}\n"
"")
        self.masukAdminButton.setObjectName("masukAdminButton")
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Hello, xxx!"))
        self.keluarButton.setText(_translate("Form", "Keluar"))
        self.masukAdminButton.setText(_translate("Form", "Masuk Ke Halaman Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
