# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/modalPesananBerlangsung.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class modalPesananBerlangsung(QtWidgets.QWidget):
    
    def __init__(self):
        super(QtWidgets.QWidget, self).__init__()
        self.setupUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 120)
        Form.setMinimumSize(QtCore.QSize(40, 120))
        Form.setMaximumSize(QtCore.QSize(16777215, 120))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Orders = QtWidgets.QFrame(Form)
        self.Orders.setMinimumSize(QtCore.QSize(0, 91))
        self.Orders.setMaximumSize(QtCore.QSize(16777215, 91))
        self.Orders.setStyleSheet("background-color: rgb(234, 216, 202);\n"
"border-radius: 8px")
        self.Orders.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Orders.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Orders.setObjectName("Orders")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Orders)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OrderID = QtWidgets.QLabel(self.Orders)
        self.OrderID.setStyleSheet("position: absolute;\n"
"width: 236px;\n"
"height: 24px;\n"
"left: 144px;\n"
"top: 228px;\n"
"\n"
"font-family: \'Sansita\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 17px;\n"
"line-height: 24px;\n"
"/* identical to box height */\n"
"\n"
"color: #000000;")
        self.OrderID.setObjectName("OrderID")
        self.horizontalLayout_2.addWidget(self.OrderID)
        self.label_11 = QtWidgets.QLabel(self.Orders)
        self.label_11.setStyleSheet("position: absolute;\n"
"width: 236px;\n"
"height: 24px;\n"
"left: 144px;\n"
"top: 228px;\n"
"\n"
"font-family: \'Sansita\';\n"
"font-style: normal;\n"
"font-weight: Bold;\n"
"font-size: 17px;\n"
"line-height: 24px;\n"
"/* identical to box height */\n"
"\n"
"color: #000000;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.Orders)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.OrderID.setText(_translate("Form", "Order ID: XXXXX"))
        self.label_11.setText(_translate("Form", "Menunggu Konfirmasi Admin"))

    def setDescriptionPesanan(self, orderId):
        self.OrderID.setText("Order ID: " + str(orderId))
        

            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = modalPesananBerlangsung()

    ui.setupUi(Form)
    ui.OrderID.setText("OrderId : 1")
    Form.show()
    sys.exit(app.exec_())
