# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.bgwidget.setAutoFillBackground(False)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: white;}")
        self.bgwidget.setObjectName("bgwidget")
        self.loginframe = QtWidgets.QFrame(self.bgwidget)
        self.loginframe.setGeometry(QtCore.QRect(330, 190, 531, 401))
        self.loginframe.setStyleSheet("QFrame#loginframe{\n"
"    background-color: rgb(244, 208, 185);\n"
"    border: 0px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")
        self.loginframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginframe.setObjectName("loginframe")
        self.usernamebox = QtWidgets.QLineEdit(self.loginframe)
        self.usernamebox.setGeometry(QtCore.QRect(30, 60, 471, 51))
        self.usernamebox.setStyleSheet("QLineEdit#usernamebox{\n"
"    background-color: white;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.usernamebox.setText("")
        self.usernamebox.setObjectName("usernamebox")
        self.usernamebox_2 = QtWidgets.QLineEdit(self.loginframe)
        self.usernamebox_2.setGeometry(QtCore.QRect(30, 170, 471, 51))
        self.usernamebox_2.setStyleSheet("QLineEdit#usernamebox_2{\n"
"    background-color: white;\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    font: 12pt \"Sansita\";\n"
"}")
        self.usernamebox_2.setText("")
        self.usernamebox_2.setObjectName("usernamebox_2")
        self.QPushButton_3 = QtWidgets.QPushButton(self.loginframe)
        self.QPushButton_3.setGeometry(QtCore.QRect(190, 300, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(11)
        self.QPushButton_3.setFont(font)
        self.QPushButton_3.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : black;\n"
"    background-color : rgb(136, 179, 160);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    background-color : rgb(85, 170, 127)\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.QPushButton_3.setCheckable(False)
        self.QPushButton_3.setObjectName("QPushButton_3")
        self.label_2 = QtWidgets.QLabel(self.loginframe)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 81, 16))
        self.label_2.setStyleSheet("font: 12pt \"Sansita\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.loginframe)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.label_3.setStyleSheet("font: 12pt \"Sansita\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.loginframe)
        self.label_5.setGeometry(QtCore.QRect(170, 360, 161, 20))
        self.label_5.setStyleSheet("font: 12pt \"Sansita\";")
        self.label_5.setObjectName("label_5")
        self.daftarButton = QtWidgets.QPushButton(self.loginframe)
        self.daftarButton.setGeometry(QtCore.QRect(320, 354, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(12)
        font.setUnderline(True)
        self.daftarButton.setFont(font)
        self.daftarButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : black;\n"
"    text-decoration: underline;\n"
"    background-color : rgb(244, 208, 185);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    text-decoration: underline; \n"
"    }")
        self.daftarButton.setCheckable(False)
        self.daftarButton.setObjectName("daftarButton")
        self.eyeButton = QtWidgets.QPushButton(self.loginframe)
        self.eyeButton.setGeometry(QtCore.QRect(450, 180, 51, 41))
        self.eyeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eyeButton.setIcon(icon)
        self.eyeButton.setIconSize(QtCore.QSize(30, 30))
        self.eyeButton.setFlat(True)
        self.eyeButton.setObjectName("eyeButton")
        self.navbar = QtWidgets.QFrame(self.bgwidget)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 1211, 91))
        self.navbar.setStyleSheet("QFrame#navbar{\n"
"    background-color: rgb(234, 216, 202);\n"
"   \n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.frame_2 = QtWidgets.QFrame(self.navbar)
        self.frame_2.setGeometry(QtCore.QRect(-10, -30, 1211, 51))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: rgb(136, 179, 160);\n"
"   \n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Logo_4 = QtWidgets.QLabel(self.navbar)
        self.Logo_4.setGeometry(QtCore.QRect(0, 0, 281, 121))
        self.Logo_4.setStyleSheet("font: 87 26pt \"Sansita\";\n"
"color : rgb(0, 0, 0) ")
        self.Logo_4.setText("")
        self.Logo_4.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/1E284E92-8854-46D1-BC93-31B6BD0FC54D-removebg-preview 1.png"))
        self.Logo_4.setScaledContents(True)
        self.Logo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_4.setObjectName("Logo_4")
        self.berandaButton_4 = QtWidgets.QPushButton(self.navbar)
        self.berandaButton_4.setGeometry(QtCore.QRect(350, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.berandaButton_4.setFont(font)
        self.berandaButton_4.setAutoFillBackground(False)
        self.berandaButton_4.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.berandaButton_4.setCheckable(False)
        self.berandaButton_4.setObjectName("berandaButton_4")
        self.tanamanButton_4 = QtWidgets.QPushButton(self.navbar)
        self.tanamanButton_4.setGeometry(QtCore.QRect(520, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.tanamanButton_4.setFont(font)
        self.tanamanButton_4.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color :  rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.tanamanButton_4.setCheckable(False)
        self.tanamanButton_4.setObjectName("tanamanButton_4")
        self.aboutButton_4 = QtWidgets.QPushButton(self.navbar)
        self.aboutButton_4.setGeometry(QtCore.QRect(670, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sansita")
        font.setPointSize(15)
        self.aboutButton_4.setFont(font)
        self.aboutButton_4.setStyleSheet("QPushButton {\n"
"    border: 0px solid #555;\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    color : rgb(53, 78, 59);\n"
"    background-color :  rgb(234, 216, 202);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    color : white;\n"
"    }")
        self.aboutButton_4.setCheckable(False)
        self.aboutButton_4.setObjectName("aboutButton_4")
        self.searchButton_3 = QtWidgets.QPushButton(self.navbar)
        self.searchButton_3.setGeometry(QtCore.QRect(930, 40, 31, 31))
        self.searchButton_3.setMouseTracking(False)
        self.searchButton_3.setAutoFillBackground(False)
        self.searchButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../img/Search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton_3.setIcon(icon1)
        self.searchButton_3.setIconSize(QtCore.QSize(31, 31))
        self.searchButton_3.setAutoDefault(True)
        self.searchButton_3.setDefault(False)
        self.searchButton_3.setFlat(True)
        self.searchButton_3.setObjectName("searchButton_3")
        self.userButton_3 = QtWidgets.QPushButton(self.navbar)
        self.userButton_3.setGeometry(QtCore.QRect(980, 35, 31, 41))
        self.userButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../img/User.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userButton_3.setIcon(icon2)
        self.userButton_3.setIconSize(QtCore.QSize(31, 41))
        self.userButton_3.setFlat(True)
        self.userButton_3.setObjectName("userButton_3")
        self.cartButton_3 = QtWidgets.QPushButton(self.navbar)
        self.cartButton_3.setGeometry(QtCore.QRect(1080, 30, 31, 51))
        self.cartButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../img/Shopping Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../../img/Shopping Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cartButton_3.setIcon(icon3)
        self.cartButton_3.setIconSize(QtCore.QSize(31, 51))
        self.cartButton_3.setAutoExclusive(False)
        self.cartButton_3.setAutoDefault(True)
        self.cartButton_3.setFlat(True)
        self.cartButton_3.setObjectName("cartButton_3")
        self.notification_4 = QtWidgets.QLabel(self.navbar)
        self.notification_4.setGeometry(QtCore.QRect(1030, 40, 31, 31))
        self.notification_4.setText("")
        self.notification_4.setPixmap(QtGui.QPixmap("../../img/Doorbell.png"))
        self.notification_4.setScaledContents(True)
        self.notification_4.setObjectName("notification_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.QPushButton_3.setText(_translate("Dialog", "Masuk"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.label_5.setText(_translate("Dialog", "Belum memiliki akun ?"))
        self.daftarButton.setText(_translate("Dialog", "Daftar"))
        self.berandaButton_4.setText(_translate("Dialog", "Beranda"))
        self.tanamanButton_4.setText(_translate("Dialog", "Tanaman"))
        self.aboutButton_4.setText(_translate("Dialog", "Tentang Kami"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
